#!/usr/bin/env python3
"""Write the English CV's publication lists: _cv/journals.bib and _cv/proceedings.bib.

Usage:  python3 scripts/build_cv_bib.py [researchmap-slug]

Which papers: every English-titled journal article and conference paper on
researchmap — the records the site's English publication list shows, preprints
aside. How each one is described: Crossref, looked up by its DOI. researchmap's
own fields are rougher (one author split in two at a comma, venue names written
several ways, article numbers missing); Crossref is also where Zotero got the
hand-made reference.bib from, so the output matches what the CV printed before.
A record without a DOI is written from researchmap.

The CV reads these with `\\nocite{*}` and the unsrt style, which prints a file
in its own order, so entries are written newest first. unsrt turns titles into
sentence case, so acronyms and names with inner capitals are braced, and SO(3)
is set as ${SO(3)}$ as the hand-made file had it. The CV owner's name is set in
bold the same way the hand-made file did: {\\textbf{Nakano}}, {\\textbf{Satoshi}}.

Output is deterministic: the same records give the same bytes, so a week with
no change commits nothing and pushes nothing to Overleaf.

When Crossref cannot be reached for a record, the entry it had in the previous
file is kept; failing that it is written from researchmap. Nothing is replaced
when the new lists are empty or less than half the old ones
(SYNC_ALLOW_SHRINK=1 overrides, as for the site's list).
"""

from __future__ import annotations

import html
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import fetch_researchmap_publications as rm  # noqa: E402
from pubsync_common import (  # noqa: E402
    REPO_ROOT,
    SyncAbort,
    allow_shrink_from_env,
    annotate,
    crossref_fetch,
    log,
)

CV_DIR = REPO_ROOT / "_cv"

# file stem -> (BibTeX entry type, what the header calls the list)
SECTIONS = {
    "journals": ("article", "Journal articles"),
    "proceedings": ("inproceedings", "Conference papers"),
}
_SECTION_FOR_CATEGORY = {"manuscripts": "journals", "conferences": "proceedings"}

# Types the site files under "manuscripts" that are not journal articles.
NOT_ARTICLES = frozenset(
    {"research_institution", "technical_report", "doctoral_thesis", "master_thesis", "misc"}
)

# Whose name is set in bold.
SELF_FAMILY = "nakano"
SELF_GIVEN_INITIAL = "s"

FIELD_ORDER = (
    "title", "booktitle", "author", "year", "journal",
    "volume", "number", "pages", "publisher", "address", "doi",
)

# No "@" anywhere in here: BibTeX reads text outside entries as a comment only
# as long as it does not look like the start of one.
HEADER = """\
% {title} for the English CV, newest first.
%
% Generated by scripts/build_cv_bib.py in GDAC-Lab/gdac-lab.github.io: the
% list comes from researchmap, the details from Crossref by DOI. Do not edit
% this file; the weekly sync overwrites it. Correct a record in researchmap.
% Read it with \\nocite{{*}} and the unsrt style, which keeps this order.

"""


# ------------------------------------------------------------------- selection


def section_for(item: dict) -> str | None:
    """"journals", "proceedings", or None when the record stays off the CV."""
    if rm.record_language(item.get("paper_title")) != "en":
        return None
    ptype = str(item.get("published_paper_type") or "").strip()
    if ptype in NOT_ARTICLES:
        return None
    return _SECTION_FOR_CATEGORY.get(rm.TYPE_TO_CATEGORY.get(ptype, ""))


def doi_of(item: dict) -> str | None:
    """The record's DOI, from see_also or identifiers, without the resolver."""
    candidates = [rm.paper_url(item)]
    identifiers = item.get("identifiers")
    if isinstance(identifiers, dict) and isinstance(identifiers.get("doi"), list):
        candidates += [str(d) for d in identifiers["doi"]]
    for text in candidates:
        m = re.search(r"10\.\d{4,9}/\S+", text or "")
        if m:
            return m.group(0).rstrip(".")
    return None


# ------------------------------------------------------------------------ text


_TAG = re.compile(r"<[^>]+>")
_MATH = re.compile(r"<((?:\w+:)?math)\b[^>]*>(.*?)</\1\s*>", re.S)


def _math_text(m: re.Match) -> str:
    # Inline MathML puts every symbol in an element of its own: SO(3) arrives
    # as <mi>S</mi><mi>O</mi><mo>(</mo>..., which must read "SO(3)", not
    # "S O ( 3 )". Drop the layout whitespace between elements, keep the text.
    return _TAG.sub("", re.sub(r">\s+<", "><", m.group(2))).strip()


def _clean(value: object) -> str:
    """Plain text from a Crossref or researchmap string: no markup, one space."""
    text = html.unescape(str(value or ""))
    text = _MATH.sub(_math_text, text)
    text = _TAG.sub(" ", text)                      # JATS tags
    text = text.replace("{", "").replace("}", "")   # would unbalance BibTeX
    return " ".join(text.split())


def tex(value: object) -> str:
    """Text safe inside a BibTeX field."""
    text = _clean(value)
    for ch in "&%#_$":
        text = text.replace(ch, "\\" + ch)
    return text


_GROUP = re.compile(r"\b(S[OE])\s*\(\s*(\d+)\s*\)")
_WORD = re.compile(r"(?<![\\\w])[A-Za-z0-9]+(?!\w)")


def _keeps_case(word: str) -> bool:
    """A word unsrt must not lowercase: LTI, IEEE, LaSalle, H2, 3D, iLQR."""
    capitals = sum(c.isupper() for c in word)
    if capitals >= 2:
        return True
    if capitals and any(c.isdigit() for c in word):
        return True
    return capitals == 1 and not word[0].isupper()


def title_tex(value: object) -> str:
    """A title for unsrt, which sets titles in sentence case."""
    text = tex(_clean(value).replace("$", ""))
    groups: list[str] = []

    def park(m: re.Match) -> str:
        groups.append(f"${{{m.group(1)}({m.group(2)})}}$")
        return f"\x00{len(groups) - 1}\x00"

    text = _GROUP.sub(park, text)
    text = _WORD.sub(lambda m: f"{{{m.group(0)}}}" if _keeps_case(m.group(0)) else m.group(0), text)
    return re.sub(r"\x00(\d+)\x00", lambda m: groups[int(m.group(1))], text)


def _name_part(value: object) -> str:
    text = _clean(value)
    # Some publishers deposit names in capitals ("NAKANO"); print them as names.
    return text.title() if text.isupper() and len(text) > 1 else text


def name_tex(family: object, given: object, literal: object = "") -> str:
    family, given = _name_part(family), _name_part(given)
    if not family:
        literal = _clean(literal)
        return f"{{{tex(literal)}}}" if literal else ""
    if family.lower() == SELF_FAMILY and given[:1].lower() == SELF_GIVEN_INITIAL:
        return f"{{\\textbf{{{tex(family)}}}}}, {{\\textbf{{{tex(given)}}}}}"
    return f"{tex(family)}, {tex(given)}" if given else tex(family)


def pages_tex(value: object) -> str:
    return re.sub(r"\s*[-–—]+\s*", "--", _clean(value))


def _first(value: object) -> str:
    if isinstance(value, list):
        return str(value[0]) if value else ""
    return str(value or "")


# --------------------------------------------------------------------- entries


def fields_from_crossref(msg: dict, kind: str, doi: str, fallback_year: str) -> dict[str, str]:
    authors = [
        name_tex(a.get("family"), a.get("given"), a.get("name"))
        for a in msg.get("author") or []
        if isinstance(a, dict)
    ]
    year = ""
    for key in ("issued", "published-print", "published-online"):
        parts = (msg.get(key) or {}).get("date-parts")
        if isinstance(parts, list) and parts and isinstance(parts[0], list) and parts[0]:
            year = str(parts[0][0])
            break
    fields = {
        "title": title_tex(_first(msg.get("title"))),
        "author": " and ".join(a for a in authors if a),
        "year": year or fallback_year,
        "pages": pages_tex(msg.get("page") or msg.get("article-number")),
        "doi": doi,
    }
    container = tex(_first(msg.get("container-title")))
    if kind == "article":
        fields.update(journal=container, volume=tex(msg.get("volume")), number=tex(msg.get("issue")))
    else:
        fields.update(
            booktitle=container,
            publisher=tex(msg.get("publisher")),
            address=tex((msg.get("event") or {}).get("location")),
        )
    return fields


def fields_from_researchmap(item: dict, kind: str, year: str) -> dict[str, str]:
    names = []
    for entry in (item.get("authors") or {}).get("en") or []:
        name = _clean(entry.get("name") if isinstance(entry, dict) else "")
        if name:
            given, _, family = name.rpartition(" ")
            names.append(name_tex(family, given))
    start, end = item.get("starting_page"), item.get("ending_page")
    fields = {
        "title": title_tex(rm.pick_localized(item.get("paper_title"), ("en",))),
        "author": " and ".join(names),
        "year": year,
        "pages": pages_tex(f"{start}-{end}" if start and end else start or ""),
    }
    container = tex(rm.pick_localized(item.get("publication_name")))
    if kind == "article":
        fields.update(journal=container, volume=tex(item.get("volume")), number=tex(item.get("number")))
    else:
        fields.update(booktitle=container, publisher=tex(rm.pick_localized(item.get("publisher"))))
    return fields


def entry(kind: str, key: str, fields: dict[str, str]) -> str:
    lines = [f"  {name} = {{{fields[name]}}}" for name in FIELD_ORDER if fields.get(name)]
    return f"@{kind}{{{key},\n" + ",\n".join(lines) + "\n}\n"


_ENTRY = re.compile(r"^@\w+\{([^,\s]+),\n.*?^\}\n", re.M | re.S)


def read_entries(text: str) -> dict[str, str]:
    """key -> entry text, from a file this script wrote."""
    return {m.group(1): m.group(0) for m in _ENTRY.finditer(text)}


def build(items: list[dict], previous: dict[str, str]) -> tuple[dict[str, list[str]], list[str]]:
    """The entries of each file, newest first, and notes on anything off."""
    rows = []
    for item in items:
        section = section_for(item)
        if section:
            date = rm.normalize_date(item.get("publication_date")) or "0000-00-00"
            rm_id = str(item.get("rm:id") or "").strip()
            rows.append((date, rm_id.zfill(12), section, rm_id, item))
    rows.sort(key=lambda r: (r[0], r[1]), reverse=True)

    sections: dict[str, list[str]] = {name: [] for name in SECTIONS}
    notes: list[str] = []
    for date, _, section, rm_id, item in rows:
        kind = SECTIONS[section][0]
        key = f"rm{rm_id}"
        doi = doi_of(item)
        msg = None
        if doi:
            try:
                msg = crossref_fetch(doi)
            except Exception as exc:  # network, rate limit, malformed response
                if key in previous:
                    sections[section].append(previous[key])
                    notes.append(f"{key}: Crossref {type(exc).__name__}: {exc} — kept the previous entry")
                    continue
                notes.append(f"{key}: Crossref {type(exc).__name__}: {exc} — written from researchmap")
            else:
                if msg is None:
                    notes.append(f"{key}: Crossref does not hold {doi} — written from researchmap")
        if msg:
            fields = fields_from_crossref(msg, kind, doi, date[:4])
        else:
            fields = fields_from_researchmap(item, kind, date[:4])
        sections[section].append(entry(kind, key, fields))
    return sections, notes


def render_file(section: str, entries: list[str]) -> str:
    return HEADER.format(title=SECTIONS[section][1]) + "\n".join(entries)


# ------------------------------------------------------------------------ main


def main() -> int:
    slug = sys.argv[1] if len(sys.argv) > 1 else "satoshi-nakano"
    try:
        items = rm.fetch_items(slug)
    except SyncAbort as exc:
        annotate("error", f"[cv] {exc}")
        return 1

    previous: dict[str, str] = {}
    for section in SECTIONS:
        path = CV_DIR / f"{section}.bib"
        if path.exists():
            previous.update(read_entries(path.read_text(encoding="utf-8")))

    sections, notes = build(items, previous)
    for note in notes:
        annotate("warning", f"[cv] {note}")

    total = sum(len(entries) for entries in sections.values())
    if total == 0 or (previous and total < len(previous) / 2 and not allow_shrink_from_env()):
        annotate(
            "error",
            f"[cv] refusing to write {total} entr(ies) over the previous {len(previous)}; "
            "the files were left as they were. Set SYNC_ALLOW_SHRINK=1 if this is intended.",
        )
        return 1

    CV_DIR.mkdir(parents=True, exist_ok=True)
    written = 0
    for section, entries in sections.items():
        path = CV_DIR / f"{section}.bib"
        content = render_file(section, entries)
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
            written += 1
    counts = ", ".join(f"{len(v)} {k}" for k, v in sections.items())
    log(f"[cv] {counts}; {written} file(s) changed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
